---
  - name: Set up a web server
    hosts: firewall
    become: true
    tasks:
      - name: Ensure Apache is installed
        apt:
          name: apache2
          state: present

      - name: Ensure Apache is running
        service:
          name: apache2
          state: started
          enabled: true

      - name: Deploy custom index.html
        copy:
          src: /path/index.html
          dest: /var/www/html/index.html
          mode: 0644
